/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\modelC1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Astronauts(props) {
  const { nodes, materials } = useGLTF('./models/modelC1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Cylinder006.geometry} material={materials['Material.004']} />
      <mesh castShadow geometry={nodes.Cylinder006_1.geometry} material={materials['Material.003']} />
      <mesh castShadow geometry={nodes.Cylinder001.geometry} material={materials['Material.017']} />
      <mesh castShadow geometry={nodes.Cylinder001_1.geometry} material={materials['Material.021']} />
      <mesh castShadow geometry={nodes.Cylinder001_2.geometry} material={materials['Material.019']} />
      <mesh castShadow geometry={nodes.Cylinder001_3.geometry} material={materials['Material.020']} />
      <mesh castShadow geometry={nodes.Cylinder001_4.geometry} material={materials['Material.018']} />
      <mesh castShadow geometry={nodes.Cylinder001_5.geometry} material={materials['Basic Glass.003']} />
    </group>
  )
}

useGLTF.preload('./models/modelC1.glb')
